export const kanbanSearchOptionDummyData: KanbanSearchOption[] = [
  'Content',
  'Label',
  'Assignee',
  'Priority',
]

export const KanbanBoardDummyData: KanbanBoardDummyDataItem[][] = [
  [
    {
      belongTo: 'TO DO',
      index: 0,
      title: '하이1',
      content: '1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈1-1 이슈',
      id: 'TEST-1',
    },
    {
      belongTo: 'TO DO',
      index: 1,
      title: '하이2',
      content: '1-2 이슈',
      id: 'TEST-2',
    },
    {
      belongTo: 'TO DO',
      index: 2,
      title: '하이3',
      content: '1-3 이슈',
      id: 'TEST-3',
    },
    {
      belongTo: 'TO DO',
      index: 3,
      title: '하4이',
      content: '1-4 이슈',
      id: 'TEST-4',
    },
  ],
  [
    {
      belongTo: 'IN PROGRESS',
      index: 0,
      title: '하이5',
      content: '2-1 이슈',
      id: 'TEST-5',
    },
    {
      belongTo: 'IN PROGRESS',
      index: 1,
      title: '하이6',
      content: '2-2 이슈',
      id: 'TEST-6',
    },
    {
      belongTo: 'IN PROGRESS',
      index: 2,
      title: '하이7',
      content: '2-3 이슈',
      id: 'TEST-7',
    },
  ],
  [
    {
      belongTo: 'COMPLETE',
      index: 0,
      title: '하이8',
      content: '3-1 이슈',
      id: 'TEST-8',
    },
    {
      belongTo: 'COMPLETE',
      index: 1,
      title: '하이9',
      content: '3-2 이슈',
      id: 'TEST-9',
    },
    {
      belongTo: 'COMPLETE',
      index: 2,
      title: '하이10',
      content: '3-3 이슈',
      id: 'TEST-10',
    },
    {
      belongTo: 'COMPLETE',
      index: 3,
      title: '하이11',
      content: '3-4 이슈',
      id: 'TEST-11',
    },
    {
      belongTo: 'COMPLETE',
      index: 4,
      title: '하이12',
      content: '3-5 이슈',
      id: 'TEST-12',
    },
    {
      belongTo: 'COMPLETE',
      index: 5,
      title: '하이13',
      content: '3-6 이슈',
      id: 'TEST-13',
    },
    {
      belongTo: 'COMPLETE',
      index: 0,
      title: '하이14',
      content: '3-1 이슈',
      id: 'TEST-14',
    },
    {
      belongTo: 'COMPLETE',
      index: 1,
      title: '하이15',
      content: '3-2 이슈',
      id: 'TEST-15',
    },
    {
      belongTo: 'COMPLETE',
      index: 2,
      title: '하이16',
      content: '3-3 이슈',
      id: 'TEST-16',
    },
    {
      belongTo: 'COMPLETE',
      index: 3,
      title: '하이17',
      content: '3-4 이슈',
      id: 'TEST-17',
    },
    {
      belongTo: 'COMPLETE',
      index: 4,
      title: '하이18',
      content: '3-5 이슈',
      id: 'TEST-18',
    },
    {
      belongTo: 'COMPLETE',
      index: 5,
      title: '하이19',
      content: '3-6 이슈',
      id: 'TEST-19',
    },
  ],
]